.\"                                                              -*- nroff -*-
.\" Copyright (c) 2017-2021  Joachim Wiberg <troglobit@gmail.com>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.a
.Dd Jan 23, 2021
.Dt ssdpd 8
.Os
.Sh NAME
.Nm ssdpd
.Nd Simple Service Discovery Protocol daemon
.Sh SYNOPSIS
.Nm
.Op Fl hnsv
.Op Fl i Ar SEC
.Op Fl l Ar LEVEL
.Op Fl r Ar SEC
.Op Fl t Ar TTL
.Op Ar IFACE Op Ar IFACE Op Ar ...
.Sh DESCRIPTION
Simple Service Discovery Protocol daemon (SSDP) for networked Linux
devices.  Useful for small and embedded systems that want to announce
themselves to UPnP capable systems, e.g. Windows.
.Pp
.Nm
is a stand-alone UNIX daemon with no external dependencies but the
standard C library.  It has a built-in web server for serving the UPnP
XML description which Windows use to present the icon, by default an
InternetGatewayDevice is announced.
.Pp
On Linux systems,
.Nm
reads
.Pa /etc/os-release ,
or
.Pa /etc/lsb-release ,
in that order to determine the distribution name and version, which
along with the system hostname, is periodically transmitted in SSDP
multicast discovery frames.  If neither file exists a built-in default
is used as server string.  On non-Linux systems the information from
.Xr uname 1
is used, since that is the canonical UNIX location for such information.
.Pp
Each SSDP capable device on a LAN has its own UUID.  This is generated
the first time
.Nm
is started and then stored in
.Pa /var/lib/misc/ssdpd.cache ,
on *BSD systems it is stored in
.Pa /var/db/ssdpd.cache .
Note, depending on your system this directory may be wiped on reboot, so
.Nm
may start up with a different UUID every time.
.Sh OPTIONS
.Bl -tag -width "-l LEVEL " -compact
.It Fl h
Show program help text
.It Fl i Ar SEC
SSDP notify interval (30-900), default 300 sec
.It Fl l Ar LEVEL
Set log level to one of the following, default
.Nm notice :
.Pp
.Bl -tag -width WARNING -compact
.It Cm none
Disable all logging
.It Cm error
Error conditions
.It Cm warning
Warning conditions
.It Cm notice
Normal but significant condition (default)
.It Cm info
Informational
.It Cm debug
Debug-level messages
.El
.Pp
.It Fl n
Run in foreground, do not daemonize by default
.It Fl r Ar SEC
Interface refresh interval (5-1800), default 600 sec
.It Fl s
Use syslog, default unless running in foreground,
.Fl n .
.It Fl t Ar TTL
TTL for multicast frames, default 2, according to the UPnP Device
Architecture (UDA)
.It Fl v
Show program version
.It Ar IFACE
By default
.Nm
runs on all IPv4 capable interfaces, except loopback.  If interface
names are given as arguments,
.Nm
will run only on them.  Interfaces are refrehed at runtime, so if
an interface given on the command line does not exist at first,
.Nm
will add them later.
.El
.Sh FILES
.Bl -tag -width /var/lib/misc/ssdpd.cache -compact
.It Pa /run/ssdpd.pid
PID file, created as soon as all setup is complete
.It Pa /etc/os-release
Linux standard base release information.  Primarily used to figure out
distribution name and release version
.It Pa /etc/lsb-release
If
.Pa /etc/os-release
does not exist,
.Nm
falls back to query this non-standard file for information on the
distribution name and release version
.It Pa /var/lib/misc/ssdpd.cache
Cached UUID (Linux), may be wiped by the system on reboot
.It Pa /var/db/ssdpd.cache
Cached UUID (*BSD), may be wiped by the system on reboot
.El
.Sh SEE ALSO
.Xr ssdp-scan 1
.Xr avahi-daemon 8
.Xr lldpd 8
.Sh AUTHORS
.An Joachim Wiberg Aq troglobit@gmail.com
